---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: howmuch
  namespace: howmuch
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/TheDoubleJo/HowMuch
